In [1]:
import pandas as pd

## Getting raw data files

In [2]:
df1 = pd.read_csv('../raw_data/Christophe-2021-10-25 10-31-58 c27.flv.csv')
df2 = pd.read_csv('../raw_data/Christophe-2021-10-25 15-01-22 c04.flv.csv')

In [3]:
df1.head()

   Unnamed: 0  timestamp_lena  Instant     duree         evenement  validation
0           0   1641568287374    49222  1.000000  Experience start           1
1           1   1635935391222   382150  0.132433    Debut conduite           1
2           2   1641568334693   383706  0.069775    Debut conduite           1
3           3   1635935603588   506260  0.186497        F.mimiques           1
4           4   1635935609899   507722  2.192817        C.Position           1

In [4]:
df2.head()

   Unnamed: 0  timestamp_lena  Instant     duree         evenement  validation
0           0   1638464153448    66032  1.000000  Experience start           1
1           1   1636990951075   349525  0.074400    Debut conduite           1
2           2   1637004290299   437875  0.166607           Endormi           0
3           3   1637004345092   585740  0.386965        F.mimiques           1
4           4   1637010089210   864774  0.990008   Grattez\frottez           1

## Plan:
- Create new column for number of file
- Add df2 to end of df1
- Ensure new file number column updates to '2' with new data

### New column

- get list of dataframe objects
- for each dataframe, loop over adding file number column value

In [5]:

def combine_data(dataframes):
    new_frames = []
    for index, df in enumerate(dataframes):
        df['file_number'] = index+1
        new_frames.append(df)
    combined_df = pd.concat(new_frames, ignore_index=True, axis=0)
    combined_df.drop('Unnamed: 0', inplace=True, axis=1)
    return combined_df

In [6]:
dataframes = [df1,df2]

combined_df = combine_data(dataframes)

In [7]:
combined_df[50:100]

,timestamp_lena,Instant,duree,evenement,validation,file_number
50,1641569429393,1748837,0.596349,C.Position,1,1
51,1635936834543,2271601,1.900674,Clignement,1,1
52,1641569520724,2284189,1.822689,C.Position,1,1
53,1635936856061,2284584,2.012273,C.Position,1,1
54,1635936875795,2295079,7.814489,Baillements,1,1
55,1641569529272,2296869,2.345875,Baillements,1,1
56,1635936891041,2312725,1.692850,Grattez\frottez,1,1
57,1641569533920,2313502,0.392602,Grattez\frottez,1,1
58,1635936917520,2347788,4.302309,Grattez\frottez,1,1
59,1641569543714,2349274,0.893261,Grattez\frottez,1,1
60,1635936938457,2354777,9.032172,Baillements,1,1
61,1641569546995,2360070,0.956069,Baillements,1,1
62,1635936968714,2413825,9.278683,Baillements,1,1
63,1641569562945,2417674,1.258361,Baillements,1,1
64,1635937049812,2462867,0.956290,Fin Experience,1,1
65,1638464153448,66032,1.000000,Experience start,1,2
66,1636990951075,349525,0.074400,Debut conduite,1,2
67,1637004290299,437875,0.166607,Endormi,0,2
68,1637004345092,585740,0.386965,F.mimiques,1,2
69,1637010089210,864774,0.990008,Grattez\frottez,1,2
70,1638464382609,865264,0.438110,Grattez\frottez,1,2
71,1637010102269,878242,0.318518,F.mimiques,1,2
72,1637010172145,1072663,7.859020,Baillements,1,2
73,1637010292386,1473996,5.302640,Baillements,1,2
74,1638464554153,1476110,3.313554,Baillements,1,2
75,1637010322163,1564575,1.805853,C.Position,0,2
76,1637010334227,1572356,2.070279,F.mimiques,1,2
77,1637010354570,1615754,2.909830,F.mimiques,1,2
78,1638464609299,1648821,4.304784,Baillements,1,2
79,1637010423842,1649075,3.785815,Baillements,1,2
80,1637010446459,1688130,5.902765,Baillements,1,2
81,1638464629168,1689294,4.823768,Baillements,1,2
82,1637012980266,1726141,6.534025,Baillements,1,2
83,1638464649044,1727513,5.159662,Baillements,1,2
84,1637012999847,1771908,0.230443,F.mimiques,1,2
85,1637013122711,2005043,0.939044,F.mimiques,1,2
86,1637013151175,2061108,1.752525,C.Position,1,2
87,1637013176424,2081105,4.114621,Baillements,1,2
88,1638464750108,2081568,3.728142,Baillements,1,2
89,1637013746165,2126151,6.811044,Baillements,1,2
90,1637056490893,2182160,5.548756,Baillements,1,2
91,1638464787196,2184159,3.765431,Baillements,1,2
92,1637056558569,2232222,6.104410,Baillements,1,2
93,1638464807342,2233848,4.124407,Baillements,1,2
94,1638464824103,2290302,0.913162,Baillements,1,2
95,1638464829929,2308006,1.325465,Baillements,1,2
96,1637056599091,2314095,0.128554,F.mimiques,1,2
97,1637056615278,2323383,1.849951,F.mimiques,1,2
98,1637056632628,2344213,2.240646,F.mimiques,0,2
99,1638464844827,2345562,0.375989,Baillements,1,2